FROM php:8.1-apache

# Instalar MySQLi para conexión a la DB
RUN docker-php-ext-install mysqli && docker-php-ext-enable mysqli

# Habilitar mod_rewrite por si hay .htaccess
RUN a2enmod rewrite

# Copiar TODO el contenido del proyecto a Apache
COPY . /var/www/html/

# Establecer permisos correctos
RUN chown -R www-data:www-data /var/www/html \
    && chmod -R 755 /var/www/html

# Puerto del contenedor
EXPOSE 80
