version: '3.8'

services:
  cashmanha:
    build: ./CashManHA
    ports:
      - "8080:80"
    depends_on:
      - mysql
    volumes:
      - ./CashManHA:/var/www/html

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoemprededores
      MYSQL_USER: root
      MYSQL_PASSWORD: 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
